title: KU2062 Agama dan Etika Protestan
logo: /assets/img/itb.png
description: Halaman informasi perkuliahan KU2062 AEP
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal

# remove view github profile/page link
github:
  is_user_page: false
  is_project_page: false